-- Viva Server initial PostgreSQL schema
-- PostgreSQL 16+
-- UUIDv7 values are generated by the Go application, not by database defaults.
-- All timestamps are UTC timestamptz. The application must SET TIME ZONE 'UTC'.

BEGIN;

CREATE SCHEMA IF NOT EXISTS viva;
SET search_path TO viva, public;

CREATE TABLE users (
    id                      uuid PRIMARY KEY,
    account_type            text NOT NULL CHECK (account_type IN ('guest', 'registered', 'admin', 'service')),
    status                  text NOT NULL CHECK (status IN ('active', 'suspended', 'deletion_pending', 'deleted')),
    display_name            varchar(80),
    locale                  varchar(16) NOT NULL DEFAULT 'zh-CN',
    timezone                varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
    token_version           integer NOT NULL DEFAULT 1 CHECK (token_version > 0),
    terms_version           varchar(32),
    terms_accepted_at       timestamptz,
    privacy_version         varchar(32),
    privacy_accepted_at     timestamptz,
    registered_at           timestamptz,
    suspended_at            timestamptz,
    suspension_reason_code  varchar(64),
    deletion_requested_at   timestamptz,
    deleted_at              timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX users_status_idx ON users (status);
CREATE INDEX users_created_at_idx ON users (created_at DESC);

-- PII is envelope-encrypted by the application. Lookup values are HMACs using a
-- server-side pepper from KMS; never use an unsalted SHA hash for email lookup.
CREATE TABLE user_identities (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    provider                   varchar(32) NOT NULL,
    provider_subject           varchar(255) NOT NULL,
    email_lookup_hmac          bytea,
    email_ciphertext           bytea,
    email_verified_at          timestamptz,
    provider_metadata          jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_subject)
);

CREATE INDEX user_identities_user_idx ON user_identities (user_id);
CREATE UNIQUE INDEX user_identities_email_lookup_unique
    ON user_identities (email_lookup_hmac)
    WHERE email_lookup_hmac IS NOT NULL AND email_verified_at IS NOT NULL;

CREATE TABLE devices (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    install_id_hash            bytea NOT NULL,
    key_thumbprint             varchar(128) NOT NULL,
    public_jwk                 jsonb NOT NULL,
    assurance_level            text NOT NULL DEFAULT 'keychain'
                               CHECK (assurance_level IN ('secure_enclave', 'keychain')),
    platform                   varchar(32) NOT NULL DEFAULT 'macos',
    device_name_ciphertext     bytea,
    app_version                varchar(32) NOT NULL,
    protocol_version           integer NOT NULL,
    os_version                 varchar(32),
    architecture               varchar(32),
    locale                     varchar(16),
    status                     text NOT NULL DEFAULT 'active'
                               CHECK (status IN ('active', 'revoked')),
    first_seen_at              timestamptz NOT NULL DEFAULT now(),
    last_seen_at               timestamptz NOT NULL DEFAULT now(),
    revoked_at                 timestamptz,
    revoked_reason_code        varchar(64),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, install_id_hash),
    UNIQUE (user_id, id),
    UNIQUE (key_thumbprint)
);

CREATE INDEX devices_user_idx ON devices (user_id, created_at DESC);
CREATE INDEX devices_status_idx ON devices (status);

CREATE TABLE refresh_token_families (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    device_id                  uuid NOT NULL,
    max_expires_at             timestamptz NOT NULL,
    revoked_at                 timestamptz,
    revoked_reason_code        varchar(64),
    reuse_detected_at          timestamptz,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX refresh_token_families_user_idx ON refresh_token_families (user_id);
CREATE INDEX refresh_token_families_device_idx ON refresh_token_families (device_id);

CREATE TABLE refresh_tokens (
    id                         uuid PRIMARY KEY,
    family_id                  uuid NOT NULL REFERENCES refresh_token_families(id),
    token_hash                 bytea NOT NULL UNIQUE,
    rotated_from_id            uuid,
    expires_at                 timestamptz NOT NULL,
    consumed_at                timestamptz,
    revoked_at                 timestamptz,
    created_ip_prefix_hmac     bytea,
    created_user_agent_hmac    bytea,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (family_id, id),
    UNIQUE (rotated_from_id),
    CHECK (rotated_from_id IS NULL OR rotated_from_id <> id),
    FOREIGN KEY (family_id, rotated_from_id) REFERENCES refresh_tokens(family_id, id)
);

CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id, created_at DESC);
CREATE INDEX refresh_tokens_expires_idx ON refresh_tokens (expires_at);

CREATE TABLE auth_challenges (
    id                         uuid PRIMARY KEY,
    kind                       text NOT NULL CHECK (kind IN ('email_otp', 'oidc_nonce', 'recent_auth')),
    purpose                    varchar(32) NOT NULL,
    subject_lookup_hmac        bytea,
    secret_hash                bytea NOT NULL,
    user_id                    uuid REFERENCES users(id),
    device_id                  uuid REFERENCES devices(id),
    attempt_count              integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts               integer NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
    expires_at                 timestamptz NOT NULL,
    consumed_at                timestamptz,
    created_ip_prefix_hmac     bytea,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX auth_challenges_subject_idx ON auth_challenges (subject_lookup_hmac, created_at DESC);
CREATE INDEX auth_challenges_expires_idx ON auth_challenges (expires_at);

CREATE TABLE plans (
    id                         uuid PRIMARY KEY,
    code                       varchar(64) NOT NULL UNIQUE,
    display_name               varchar(120) NOT NULL,
    description                text,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE plan_versions (
    id                         uuid PRIMARY KEY,
    plan_id                    uuid NOT NULL REFERENCES plans(id),
    version                    integer NOT NULL CHECK (version > 0),
    status                     text NOT NULL DEFAULT 'draft'
                               CHECK (status IN ('draft', 'active', 'retired')),
    currency                   char(3) NOT NULL,
    price_minor                bigint NOT NULL CHECK (price_minor >= 0),
    billing_interval           text NOT NULL CHECK (billing_interval IN ('one_time', 'month', 'year')),
    asr_audio_ms_limit         bigint NOT NULL CHECK (asr_audio_ms_limit >= 0),
    llm_input_tokens_limit     bigint NOT NULL DEFAULT 0 CHECK (llm_input_tokens_limit >= 0),
    llm_output_tokens_limit    bigint NOT NULL DEFAULT 0 CHECK (llm_output_tokens_limit >= 0),
    llm_request_limit          bigint NOT NULL DEFAULT 0 CHECK (llm_request_limit >= 0),
    max_asr_concurrency        integer NOT NULL DEFAULT 1 CHECK (max_asr_concurrency > 0),
    max_session_ms             integer NOT NULL DEFAULT 75000 CHECK (max_session_ms BETWEEN 1000 AND 75000),
    allowed_model_tiers        jsonb NOT NULL DEFAULT '["fast"]'::jsonb,
    features                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    effective_from             timestamptz NOT NULL,
    sales_end_at               timestamptz,
    retired_at                 timestamptz,
    created_by                 uuid REFERENCES users(id),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (plan_id, version)
);

CREATE INDEX plan_versions_effective_idx ON plan_versions (effective_from DESC);

CREATE TABLE subscriptions (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    plan_version_id            uuid NOT NULL REFERENCES plan_versions(id),
    provider                   varchar(32) NOT NULL,
    external_customer_id       varchar(255),
    external_subscription_id   varchar(255),
    status                     text NOT NULL
                               CHECK (status IN ('trialing', 'active', 'past_due', 'paused', 'cancelled', 'expired')),
    current_period_start       timestamptz NOT NULL,
    current_period_end         timestamptz NOT NULL,
    cancel_at_period_end       boolean NOT NULL DEFAULT false,
    cancelled_at               timestamptz,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX subscriptions_provider_external_unique
    ON subscriptions (provider, external_subscription_id)
    WHERE external_subscription_id IS NOT NULL;
CREATE INDEX subscriptions_user_idx ON subscriptions (user_id, created_at DESC);
CREATE INDEX subscriptions_status_idx ON subscriptions (status, current_period_end);
CREATE UNIQUE INDEX subscriptions_one_current_per_user
    ON subscriptions (user_id)
    WHERE status IN ('trialing', 'active', 'past_due', 'paused');

CREATE TABLE billing_orders (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    plan_version_id            uuid NOT NULL REFERENCES plan_versions(id),
    provider                   varchar(32) NOT NULL,
    external_order_id          varchar(255),
    status                     text NOT NULL
                               CHECK (status IN ('created', 'pending_payment', 'paid', 'fulfilled', 'cancelled', 'expired', 'refund_pending', 'partially_refunded', 'refunded', 'refund_failed')),
    currency                   char(3) NOT NULL,
    amount_minor               bigint NOT NULL CHECK (amount_minor >= 0),
    refunded_amount_minor      bigint NOT NULL DEFAULT 0,
    idempotency_key            uuid NOT NULL,
    provider_payload_hash      bytea,
    paid_at                    timestamptz,
    fulfilled_at               timestamptz,
    cancelled_at               timestamptz,
    refunded_at                timestamptz,
    expires_at                 timestamptz,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, provider, currency),
    UNIQUE (user_id, idempotency_key),
    CHECK (refunded_amount_minor BETWEEN 0 AND amount_minor)
);

CREATE UNIQUE INDEX billing_orders_external_unique
    ON billing_orders (provider, external_order_id)
    WHERE external_order_id IS NOT NULL;
CREATE INDEX billing_orders_user_idx ON billing_orders (user_id, created_at DESC);
CREATE INDEX billing_orders_status_idx ON billing_orders (status, created_at);

CREATE TABLE billing_refunds (
    id                         uuid PRIMARY KEY,
    order_id                   uuid NOT NULL,
    provider                   varchar(32) NOT NULL,
    external_refund_id         varchar(255),
    status                     text NOT NULL DEFAULT 'requested'
                               CHECK (status IN ('requested', 'pending', 'succeeded', 'failed', 'cancelled')),
    currency                   char(3) NOT NULL,
    amount_minor               bigint NOT NULL CHECK (amount_minor > 0),
    idempotency_key            uuid NOT NULL,
    reason                     text NOT NULL,
    ticket_id                  varchar(128) NOT NULL,
    requested_by               uuid NOT NULL REFERENCES users(id),
    provider_payload_hash      bytea,
    failure_code               varchar(64),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    completed_at               timestamptz,
    UNIQUE (order_id, idempotency_key),
    FOREIGN KEY (order_id, provider, currency)
        REFERENCES billing_orders(id, provider, currency)
);

CREATE UNIQUE INDEX billing_refunds_external_unique
    ON billing_refunds (provider, external_refund_id)
    WHERE external_refund_id IS NOT NULL;
CREATE INDEX billing_refunds_order_idx ON billing_refunds (order_id, created_at DESC);
CREATE INDEX billing_refunds_status_idx ON billing_refunds (status, created_at);

CREATE TABLE incoming_webhooks (
    id                         uuid PRIMARY KEY,
    provider                   varchar(32) NOT NULL,
    external_event_id          varchar(255) NOT NULL,
    event_type                 varchar(128) NOT NULL,
    payload_hash               bytea NOT NULL,
    raw_payload_ciphertext     bytea,
    provider_created_at        timestamptz,
    status                     text NOT NULL DEFAULT 'received'
                               CHECK (status IN ('received', 'processing', 'processed', 'retry', 'dead_letter', 'ignored')),
    attempt_count              integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at            timestamptz,
    lease_owner                varchar(128),
    lease_expires_at           timestamptz,
    last_error_code            varchar(64),
    received_at                timestamptz NOT NULL DEFAULT now(),
    processed_at               timestamptz,
    UNIQUE (provider, external_event_id)
);

CREATE INDEX incoming_webhooks_pending_idx
    ON incoming_webhooks (status, next_attempt_at)
    WHERE status IN ('received', 'retry');
CREATE INDEX incoming_webhooks_lease_idx
    ON incoming_webhooks (lease_expires_at)
    WHERE status = 'processing';

-- No provider secret is stored here. secret_ref points to KMS/Secret Manager.
CREATE TABLE provider_accounts (
    id                         uuid PRIMARY KEY,
    provider                   text NOT NULL CHECK (provider IN ('volc_asr', 'volc_ark', 'mock_asr', 'mock_llm')),
    purpose                    text NOT NULL CHECK (purpose IN ('asr', 'llm')),
    region                     varchar(64) NOT NULL,
    endpoint                   text NOT NULL,
    resource_id                varchar(255),
    model_alias                varchar(128),
    secret_ref                 text NOT NULL,
    secret_version             varchar(128),
    status                     text NOT NULL DEFAULT 'active'
                               CHECK (status IN ('active', 'disabled', 'unhealthy')),
    weight                     integer NOT NULL DEFAULT 100 CHECK (weight >= 0),
    max_concurrency            integer CHECK (max_concurrency IS NULL OR max_concurrency > 0),
    last_health_at             timestamptz,
    last_error_code            varchar(64),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX provider_accounts_route_idx ON provider_accounts (purpose, region, status);

CREATE TABLE asr_sessions (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    device_id                  uuid NOT NULL,
    provider_account_id        uuid REFERENCES provider_accounts(id),
    plan_version_id            uuid REFERENCES plan_versions(id),
    instance_id                varchar(128),
    trace_id                   varchar(64) NOT NULL,
    request_id                 uuid NOT NULL,
    status                     text NOT NULL
                               CHECK (status IN ('accepted', 'streaming', 'completed', 'cancelled', 'failed', 'drained', 'admin_terminated')),
    client_version             varchar(32) NOT NULL,
    protocol_version           integer NOT NULL,
    region                     varchar(64),
    started_at                 timestamptz NOT NULL,
    first_audio_at             timestamptz,
    upstream_connected_at      timestamptz,
    first_partial_at           timestamptz,
    last_audio_at              timestamptz,
    final_at                   timestamptz,
    completed_at               timestamptz,
    audio_bytes                bigint NOT NULL DEFAULT 0 CHECK (audio_bytes >= 0),
    audio_ms                   bigint NOT NULL DEFAULT 0 CHECK (audio_ms >= 0),
    upstream_request_id        varchar(128),
    upstream_connect_id        varchar(128),
    upstream_log_id            varchar(255),
    end_window_ms              integer,
    hotword_count              integer NOT NULL DEFAULT 0 CHECK (hotword_count >= 0),
    dialog_context_count       integer NOT NULL DEFAULT 0 CHECK (dialog_context_count >= 0),
    first_frame_rewritten      boolean NOT NULL DEFAULT false,
    error_code                 varchar(64),
    provider_error_code        varchar(64),
    error_retryable            boolean,
    timing                     jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, request_id),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX asr_sessions_user_idx ON asr_sessions (user_id, started_at DESC);
CREATE INDEX asr_sessions_device_idx ON asr_sessions (device_id, started_at DESC);
CREATE INDEX asr_sessions_status_idx ON asr_sessions (status, started_at DESC);
CREATE INDEX asr_sessions_upstream_log_idx ON asr_sessions (upstream_log_id)
    WHERE upstream_log_id IS NOT NULL;

CREATE TABLE llm_requests (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    device_id                  uuid NOT NULL,
    asr_session_id             uuid REFERENCES asr_sessions(id),
    provider_account_id        uuid REFERENCES provider_accounts(id),
    plan_version_id            uuid REFERENCES plan_versions(id),
    request_id                 uuid NOT NULL,
    idempotency_key            uuid NOT NULL,
    trace_id                   varchar(64) NOT NULL,
    mode                       text NOT NULL CHECK (mode IN ('polish', 'course_correction', 'both')),
    model_tier                 varchar(32) NOT NULL,
    provider_model             varchar(255),
    prompt_version             varchar(64) NOT NULL,
    status                     text NOT NULL
                               CHECK (status IN ('reserved', 'streaming', 'completed', 'failed', 'cancelled')),
    input_chars                integer NOT NULL DEFAULT 0 CHECK (input_chars >= 0),
    output_chars               integer NOT NULL DEFAULT 0 CHECK (output_chars >= 0),
    input_tokens               bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens              bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    usage_estimated            boolean NOT NULL DEFAULT false,
    started_at                 timestamptz NOT NULL,
    first_token_at             timestamptz,
    completed_at               timestamptz,
    provider_request_id        varchar(255),
    error_code                 varchar(64),
    provider_error_code        varchar(64),
    timing                     jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, idempotency_key),
    UNIQUE (user_id, request_id),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX llm_requests_user_idx ON llm_requests (user_id, started_at DESC);
CREATE INDEX llm_requests_status_idx ON llm_requests (status, started_at DESC);

-- Append-only usage facts. Corrections are new rows with positive/negative quantity.
CREATE TABLE usage_ledger (
    id                         bigserial PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    device_id                  uuid,
    source_type                text NOT NULL CHECK (source_type IN ('asr_session', 'llm_request', 'quota_adjustment', 'subscription', 'trial')),
    source_id                  uuid NOT NULL,
    resource                   varchar(64) NOT NULL,
    quantity                   bigint NOT NULL,
    unit                       varchar(32) NOT NULL,
    period_start               timestamptz NOT NULL,
    period_end                 timestamptz NOT NULL,
    provider                   varchar(64),
    provider_resource          varchar(255),
    provider_cost_microunits   bigint NOT NULL DEFAULT 0,
    currency                   char(3),
    price_snapshot             jsonb NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key            varchar(255) NOT NULL UNIQUE,
    occurred_at                timestamptz NOT NULL,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    metadata                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (period_end > period_start),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX usage_ledger_user_period_idx
    ON usage_ledger (user_id, period_start, resource, occurred_at DESC);
CREATE INDEX usage_ledger_source_idx ON usage_ledger (source_type, source_id);
CREATE INDEX usage_ledger_occurred_idx ON usage_ledger (occurred_at DESC);

CREATE TABLE usage_counters (
    user_id                    uuid NOT NULL REFERENCES users(id),
    period_start               timestamptz NOT NULL,
    period_end                 timestamptz NOT NULL,
    resource                   varchar(64) NOT NULL,
    quantity                   bigint NOT NULL DEFAULT 0,
    reserved_quantity          bigint NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, period_start, resource),
    CHECK (period_end > period_start)
);

CREATE TABLE quota_adjustments (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    resource                   varchar(64) NOT NULL,
    quantity                   bigint NOT NULL,
    reason_code                varchar(64) NOT NULL,
    reason                     text NOT NULL,
    starts_at                  timestamptz NOT NULL,
    expires_at                 timestamptz,
    idempotency_key            uuid NOT NULL,
    created_by                 uuid NOT NULL REFERENCES users(id),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, idempotency_key),
    CHECK (expires_at IS NULL OR expires_at > starts_at)
);

CREATE INDEX quota_adjustments_user_idx ON quota_adjustments (user_id, starts_at DESC);

-- Generic idempotency cache. Content-bearing responses must be encrypted and
-- content_expires_at kept short; a cleanup worker must NULL expired ciphertext.
CREATE TABLE idempotency_keys (
    subject_id                 uuid NOT NULL,
    route                      varchar(255) NOT NULL,
    idempotency_key            uuid NOT NULL,
    request_hash               bytea NOT NULL,
    status                     text NOT NULL CHECK (status IN ('in_progress', 'completed', 'failed')),
    response_status            integer,
    response_headers           jsonb,
    response_body_ciphertext   bytea,
    content_expires_at         timestamptz,
    expires_at                 timestamptz NOT NULL,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (subject_id, route, idempotency_key)
);

CREATE INDEX idempotency_keys_expiry_idx ON idempotency_keys (expires_at);

CREATE TABLE privacy_requests (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    kind                       text NOT NULL CHECK (kind IN ('export', 'deletion')),
    status                     text NOT NULL
                               CHECK (status IN ('requested', 'processing', 'ready', 'completed', 'cancelled', 'failed')),
    idempotency_key            uuid NOT NULL,
    requested_at               timestamptz NOT NULL DEFAULT now(),
    grace_expires_at           timestamptz,
    object_key_ciphertext      bytea,
    object_expires_at          timestamptz,
    completed_at               timestamptz,
    cancelled_at               timestamptz,
    error_code                 varchar(64),
    metadata                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (user_id, idempotency_key)
);

CREATE INDEX privacy_requests_user_idx ON privacy_requests (user_id, requested_at DESC);
CREATE INDEX privacy_requests_pending_idx ON privacy_requests (status, requested_at)
    WHERE status IN ('requested', 'processing');

CREATE TABLE diagnostic_reports (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    device_id                  uuid NOT NULL,
    session_id                 uuid,
    category                   text NOT NULL CHECK (category IN ('auth', 'asr_connect', 'asr_result', 'polish', 'billing', 'other')),
    sanitized_events           jsonb NOT NULL,
    contains_audio             boolean NOT NULL DEFAULT false CHECK (contains_audio = false),
    contains_transcript        boolean NOT NULL DEFAULT false CHECK (contains_transcript = false),
    idempotency_key            uuid NOT NULL,
    expires_at                 timestamptz NOT NULL,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, idempotency_key),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX diagnostic_reports_user_idx ON diagnostic_reports (user_id, created_at DESC);
CREATE INDEX diagnostic_reports_expiry_idx ON diagnostic_reports (expires_at);

CREATE TABLE diagnostic_uploads (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    device_id                  uuid NOT NULL,
    object_key_ciphertext      bytea NOT NULL,
    file_name_ciphertext       bytea NOT NULL,
    content_type               varchar(64) NOT NULL
                               CHECK (content_type IN ('application/zip', 'audio/wav', 'audio/x-wav', 'text/plain')),
    size_bytes                 bigint NOT NULL CHECK (size_bytes BETWEEN 1 AND 10485760),
    sha256                     bytea NOT NULL CHECK (octet_length(sha256) = 32),
    contains_audio             boolean NOT NULL DEFAULT false,
    contains_transcript        boolean NOT NULL DEFAULT false,
    explicit_consent_at        timestamptz NOT NULL,
    status                     text NOT NULL DEFAULT 'issued'
                               CHECK (status IN ('issued', 'uploaded', 'expired', 'deleted')),
    idempotency_key            uuid NOT NULL,
    upload_expires_at          timestamptz NOT NULL,
    object_expires_at          timestamptz NOT NULL,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, idempotency_key),
    CHECK (object_expires_at > upload_expires_at),
    FOREIGN KEY (user_id, device_id) REFERENCES devices(user_id, id)
);

CREATE INDEX diagnostic_uploads_user_idx ON diagnostic_uploads (user_id, created_at DESC);
CREATE INDEX diagnostic_uploads_expiry_idx ON diagnostic_uploads (status, object_expires_at);

CREATE TABLE client_configs (
    id                         uuid PRIMARY KEY,
    version                    integer NOT NULL UNIQUE CHECK (version > 0),
    status                     text NOT NULL CHECK (status IN ('draft', 'published', 'retired')),
    minimum_client_version     varchar(32) NOT NULL,
    rollout_percentage         numeric(5,2) NOT NULL DEFAULT 100 CHECK (rollout_percentage BETWEEN 0 AND 100),
    audience_rules             jsonb NOT NULL DEFAULT '{}'::jsonb,
    config                     jsonb NOT NULL,
    canonical_hash             bytea NOT NULL,
    signature                  bytea,
    published_at               timestamptz,
    retired_at                 timestamptz,
    created_by                 uuid NOT NULL REFERENCES users(id),
    created_at                 timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX client_configs_status_idx ON client_configs (status, version DESC);

CREATE TABLE admin_role_bindings (
    user_id                    uuid NOT NULL REFERENCES users(id),
    role                       text NOT NULL
                               CHECK (role IN ('support_readonly', 'support_agent', 'billing_admin', 'security_admin', 'platform_admin', 'super_admin')),
    created_by                 uuid NOT NULL REFERENCES users(id),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    revoked_at                 timestamptz,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE support_notes (
    id                         uuid PRIMARY KEY,
    user_id                    uuid NOT NULL REFERENCES users(id),
    actor_id                   uuid NOT NULL REFERENCES users(id),
    category                   text NOT NULL CHECK (category IN ('support', 'billing', 'security', 'other')),
    note                       varchar(1000) NOT NULL,
    ticket_id                  varchar(128) NOT NULL,
    idempotency_key            uuid NOT NULL,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (actor_id, idempotency_key)
);

CREATE INDEX support_notes_user_idx ON support_notes (user_id, created_at DESC);

CREATE TABLE audit_logs (
    id                         bigserial PRIMARY KEY,
    actor_type                 text NOT NULL CHECK (actor_type IN ('user', 'admin', 'service', 'system')),
    actor_id                   uuid,
    actor_roles                jsonb NOT NULL DEFAULT '[]'::jsonb,
    action                     varchar(128) NOT NULL,
    target_type                varchar(64),
    target_id                  varchar(255),
    request_id                 uuid,
    trace_id                   varchar(64),
    ip_prefix_hmac             bytea,
    result                     text NOT NULL CHECK (result IN ('success', 'denied', 'failed')),
    reason                     text,
    change_summary             jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at                 timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_actor_idx ON audit_logs (actor_id, created_at DESC);
CREATE INDEX audit_logs_target_idx ON audit_logs (target_type, target_id, created_at DESC);
CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC);

CREATE TABLE transactional_outbox (
    id                         uuid PRIMARY KEY,
    topic                      varchar(128) NOT NULL,
    aggregate_type             varchar(64) NOT NULL,
    aggregate_id               uuid NOT NULL,
    payload                    jsonb NOT NULL,
    status                     text NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending', 'processing', 'published', 'dead_letter')),
    attempt_count              integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at            timestamptz NOT NULL DEFAULT now(),
    lease_owner                varchar(128),
    lease_expires_at           timestamptz,
    last_error_code            varchar(64),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    published_at               timestamptz
);

CREATE INDEX transactional_outbox_pending_idx
    ON transactional_outbox (status, next_attempt_at, created_at)
    WHERE status IN ('pending', 'processing');
CREATE INDEX transactional_outbox_lease_idx
    ON transactional_outbox (lease_expires_at)
    WHERE status = 'processing';

CREATE TABLE provider_daily_reconciliation (
    id                         uuid PRIMARY KEY,
    provider                   varchar(64) NOT NULL,
    resource                   varchar(128) NOT NULL,
    usage_date                 date NOT NULL,
    internal_quantity          bigint NOT NULL,
    provider_quantity          bigint,
    internal_cost_microunits   bigint NOT NULL DEFAULT 0,
    provider_cost_microunits   bigint,
    difference_ratio           numeric(12,6),
    status                     text NOT NULL CHECK (status IN ('pending', 'matched', 'mismatch', 'waived')),
    details                    jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, resource, usage_date)
);

-- Runtime database roles must also omit UPDATE/DELETE grants on immutable
-- tables. These triggers provide defense in depth and make accidental writes
-- fail loudly; corrections are represented by new rows.
CREATE OR REPLACE FUNCTION reject_immutable_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER usage_ledger_reject_mutation
BEFORE UPDATE OR DELETE ON usage_ledger
FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();

CREATE TRIGGER audit_logs_reject_mutation
BEFORE UPDATE OR DELETE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();

CREATE OR REPLACE FUNCTION protect_published_plan_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status IN ('active', 'retired') THEN
            RAISE EXCEPTION 'published plan version cannot be deleted' USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.status IN ('active', 'retired') AND
       (to_jsonb(NEW) - ARRAY['status', 'sales_end_at', 'retired_at', 'updated_at'])
       IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['status', 'sales_end_at', 'retired_at', 'updated_at']) THEN
        RAISE EXCEPTION 'published plan version fields are immutable' USING ERRCODE = '55000';
    END IF;

    IF OLD.status = 'active' AND NEW.status NOT IN ('active', 'retired') THEN
        RAISE EXCEPTION 'active plan version may only remain active or retire' USING ERRCODE = '55000';
    END IF;

    IF OLD.status = 'retired' AND NEW.status <> 'retired' THEN
        RAISE EXCEPTION 'retired plan version cannot be reactivated' USING ERRCODE = '55000';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER plan_versions_protect_published
BEFORE UPDATE OR DELETE ON plan_versions
FOR EACH ROW EXECUTE FUNCTION protect_published_plan_version();

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER user_identities_set_updated_at
BEFORE UPDATE ON user_identities
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER devices_set_updated_at
BEFORE UPDATE ON devices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER plans_set_updated_at
BEFORE UPDATE ON plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER plan_versions_set_updated_at
BEFORE UPDATE ON plan_versions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER subscriptions_set_updated_at
BEFORE UPDATE ON subscriptions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER billing_orders_set_updated_at
BEFORE UPDATE ON billing_orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER billing_refunds_set_updated_at
BEFORE UPDATE ON billing_refunds
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER provider_accounts_set_updated_at
BEFORE UPDATE ON provider_accounts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER asr_sessions_set_updated_at
BEFORE UPDATE ON asr_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER llm_requests_set_updated_at
BEFORE UPDATE ON llm_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER idempotency_keys_set_updated_at
BEFORE UPDATE ON idempotency_keys
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER diagnostic_uploads_set_updated_at
BEFORE UPDATE ON diagnostic_uploads
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER provider_daily_reconciliation_set_updated_at
BEFORE UPDATE ON provider_daily_reconciliation
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
