import Foundation
import AppKit
import Carbon.HIToolbox

/// 把识别出来的文本写进当前光标处。
///
/// ⚠️ 这是整个项目最脆弱的一环，而且失败往往是**静默**的。
/// 策略：剪贴板 + ⌘V 为主（兼容面最广），CGEvent 逐字为辅（不污染剪贴板）。
/// **只做追加，绝不做退格回改** —— 算错一次就会不可逆地删掉用户自己的文字。
enum TextInjector {

    /// 已知的「慢消费者」——读剪贴板慢的宿主。
    ///
    /// ⚠️ 用**前缀/关键字**匹配而不是精确 bundle id：Electron 系（VS Code / Slack /
    ///    飞书 / Notion / Obsidian / Cursor）同样以读剪贴板慢出名，精确名单永远漏。
    ///    恢复晚一点用户几乎无感，粘错内容却是不可逆的 —— 宁可保守。
    private static let slowPasteHints: [String] = [
        "iterm", "warp", "ghostty", "terminal", "alacritty", "kitty",
        "vscode", "code", "cursor", "slack", "lark", "feishu",
        "notion", "obsidian", "discord", "electron",
    ]

    private static func isSlowConsumer(_ bundleId: String?) -> Bool {
        guard let b = bundleId?.lowercased() else { return false }
        return slowPasteHints.contains { b.contains($0) }
    }

    /// Secure Event Input 开启时（密码框、iTerm2 的 Secure Keyboard Entry、1Password 前台），
    /// CGEventTap 与合成按键**全部失效且没有任何错误返回**。必须主动检测。
    static var isSecureInputEnabled: Bool { IsSecureEventInputEnabled() }

    static var frontmostBundleId: String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    // MARK: - 入口

    enum Result {
        case injected
        case copiedOnly(reason: String)   // 没能自动上屏，已复制到剪贴板
    }

    @discardableResult
    static func commit(_ text: String, config: Config) -> Result {
        guard !text.isEmpty else { return .injected }

        if isSecureInputEnabled {
            copyToClipboard(text, transient: false)
            return .copiedOnly(reason: "当前 App 开启了安全键盘输入")
        }
        guard AXIsProcessTrusted() else {
            copyToClipboard(text, transient: false)
            return .copiedOnly(reason: "缺少「辅助功能」权限")
        }

        if config.useClipboardPaste {
            pasteViaClipboard(text, config: config)
        } else {
            typeUnicode(text)
        }
        return .injected
    }

    // MARK: - 路线一：剪贴板 + ⌘V

    /// 待恢复的用户原始剪贴板。
    ///
    /// ⚠️ 逐句上屏时会连续调用本方法多次。原来每次都重新抓一份 backup，
    ///   第 2 句抓到的其实是第 1 句刚写进去的识别文本，而第 1 句的恢复闭包
    ///   又因为 changeCount 变了而直接 return —— 结果用户真正的剪贴板内容
    ///   被静默替换成「倒数第二个识别分句」，且带 Transient 标记连剪贴板
    ///   管理器都不留历史，完全不可恢复。这是静默数据丢失。
    ///   改成：整段说话期间只抓一次，恢复也只做一次。
    private static var pendingBackup: [[NSPasteboard.PasteboardType: Data]]?
    private static var restoreWork: DispatchWorkItem?

    private static func pasteViaClipboard(_ text: String, config: Config) {
        let pb = NSPasteboard.general

        // 1. 只在没有待恢复备份时才抓 —— 保证拿到的是用户自己的内容
        if pendingBackup == nil {
            var backup: [[NSPasteboard.PasteboardType: Data]] = []
            for item in pb.pasteboardItems ?? [] {
                var d: [NSPasteboard.PasteboardType: Data] = [:]
                for t in item.types { d[t] = item.data(forType: t) }
                if !d.isEmpty { backup.append(d) }
            }
            pendingBackup = backup
        }

        // 2. 写入并打上「临时内容」标记 —— Maccy / Paste 等剪贴板管理器
        //    默认忽略这些类型，用户的剪贴板历史不会被污染。见 nspasteboard.org
        pb.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: .init("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: .init("org.nspasteboard.AutoGeneratedType"))
        pb.writeObjects([item])
        let changeCountAfterWrite = pb.changeCount

        // 3. 模拟 ⌘V
        postCommandV()

        // 4. 延迟恢复。恢复太早目标 App 还没读走，会粘出旧内容。
        var delayMs = max(config.clipboardRestoreDelayMs, 600)   // 200ms 太赌了
        if isSlowConsumer(frontmostBundleId) {
            delayMs = max(delayMs, 1500)      // typeflux 实测：慢消费者要 1.5s
        }

        // 每次上屏都把恢复时间往后推，整段说完后才真正恢复一次
        restoreWork?.cancel()
        let work = DispatchWorkItem {
            defer { pendingBackup = nil; restoreWork = nil }
            // 期间用户自己复制过东西就不要覆盖他
            guard pb.changeCount == changeCountAfterWrite else { return }
            guard let backup = pendingBackup, !backup.isEmpty else {
                pb.clearContents(); return
            }
            pb.clearContents()
            let items: [NSPasteboardItem] = backup.map { dict in
                let it = NSPasteboardItem()
                for (t, d) in dict { it.setData(d, forType: t) }
                return it
            }
            pb.writeObjects(items)
        }
        restoreWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(delayMs), execute: work)
    }

    private static func postCommandV() {
        let src = CGEventSource(stateID: .combinedSessionState)
        let vKey = CGKeyCode(kVK_ANSI_V)
        guard let down = CGEvent(keyboardEventSource: src, virtualKey: vKey, keyDown: true),
              let up = CGEvent(keyboardEventSource: src, virtualKey: vKey, keyDown: false)
        else { return }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.post(tap: .cgSessionEventTap)
        usleep(1500)
        up.post(tap: .cgSessionEventTap)
    }

    // MARK: - 路线二：CGEvent 逐字键入

    /// 四个已知坑（全部来自 enigo 的 macOS 实现）：
    /// ① 单次调用超过 20 个 UTF-16 单元会被**静默截断**
    /// ② 以 \n \r \t 开头的块整块静默失败 → 换行单独用 Return 键码发
    /// ③ 必须显式清空 flags，否则用户按住的 ⌘ 会污染注入（变成快捷键）
    /// ④ 不加间隔某些 App 会丢字
    static func typeUnicode(_ text: String) {
        let src = CGEventSource(stateID: .privateState)

        for line in splitKeepingNewlines(text) {
            if line == "\n" || line == "\r" {
                postKey(CGKeyCode(kVK_Return), src: src)
                continue
            }
            if line == "\t" {
                postKey(CGKeyCode(kVK_Tab), src: src)
                continue
            }
            for chunk in chunkByGrapheme(line, maxUTF16: 20) {
                guard let down = CGEvent(keyboardEventSource: src, virtualKey: 0, keyDown: true),
                      let up = CGEvent(keyboardEventSource: src, virtualKey: 0, keyDown: false)
                else { continue }
                var units = Array(chunk.utf16)
                down.flags = []                       // 坑③
                up.flags = []
                down.keyboardSetUnicodeString(stringLength: units.count, unicodeString: &units)
                up.keyboardSetUnicodeString(stringLength: units.count, unicodeString: &units)
                down.post(tap: .cgSessionEventTap)
                up.post(tap: .cgSessionEventTap)
                usleep(2000)                          // 坑④
            }
        }
    }

    private static func postKey(_ code: CGKeyCode, src: CGEventSource?) {
        guard let d = CGEvent(keyboardEventSource: src, virtualKey: code, keyDown: true),
              let u = CGEvent(keyboardEventSource: src, virtualKey: code, keyDown: false)
        else { return }
        d.flags = []; u.flags = []
        d.post(tap: .cgSessionEventTap)
        u.post(tap: .cgSessionEventTap)
        usleep(2000)
    }

    /// 把换行/Tab 拆成独立元素，其余按原样保留（坑②）
    private static func splitKeepingNewlines(_ s: String) -> [String] {
        var out: [String] = []
        var buf = ""
        for ch in s {
            if ch == "\n" || ch == "\r" || ch == "\t" {
                if !buf.isEmpty { out.append(buf); buf = "" }
                out.append(String(ch))
            } else {
                buf.append(ch)
            }
        }
        if !buf.isEmpty { out.append(buf) }
        return out
    }

    /// 按 UTF-16 长度分块，但**不在字素簇中间切断**（否则 emoji / 代理对会变乱码，坑①）
    private static func chunkByGrapheme(_ s: String, maxUTF16: Int) -> [String] {
        var out: [String] = []
        var cur = ""
        var curLen = 0
        for ch in s {
            let l = String(ch).utf16.count
            if curLen + l > maxUTF16, !cur.isEmpty {
                out.append(cur); cur = ""; curLen = 0
            }
            cur.append(ch); curLen += l
        }
        if !cur.isEmpty { out.append(cur) }
        return out
    }

    // MARK: -

    static func copyToClipboard(_ text: String, transient: Bool) {
        let pb = NSPasteboard.general
        pb.clearContents()
        if transient {
            let it = NSPasteboardItem()
            it.setString(text, forType: .string)
            it.setData(Data(), forType: .init("org.nspasteboard.TransientType"))
            pb.writeObjects([it])
        } else {
            pb.setString(text, forType: .string)
        }
    }
}
